// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(
    ////////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
    input logic           ADC_CLK_10,
`endif
    ////////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
    input logic           MAX10_CLK1_50,
`endif
    ////////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
    input logic           MAX10_CLK2_50,
`endif

    ////////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
    output logic [12:0]   DRAM_ADDR,
    output logic [1:0]    DRAM_BA,
    output logic          DRAM_CAS_N,
    output logic          DRAM_CKE,
    output logic          DRAM_CLK,
    output logic          DRAM_CS_N,
    inout  logic [15:0]   DRAM_DQ,
    output logic          DRAM_LDQM,
    output logic          DRAM_RAS_N,
    output logic          DRAM_UDQM,
    output logic          DRAM_WE_N,
`endif

    ////////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
    output logic [7:0]    HEX0,
`endif
`ifdef ENABLE_HEX1
    output logic [7:0]    HEX1,
`endif
`ifdef ENABLE_HEX2
    output logic [7:0]    HEX2,
`endif
`ifdef ENABLE_HEX3
    output logic [7:0]    HEX3,
`endif
`ifdef ENABLE_HEX4
    output logic [7:0]    HEX4,
`endif
`ifdef ENABLE_HEX5
    output logic [7:0]    HEX5,
`endif

    ////////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
    input logic [1:0]      KEY,
`endif

    ////////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
    output logic [9:0]     LEDR,
`endif

    ////////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
    input logic [9:0]      SW,
`endif

    ////////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
    output logic [3:0]     VGA_B,
    output logic [3:0]     VGA_G,
    output logic           VGA_HS,
    output logic [3:0]     VGA_R,
    output logic           VGA_VS,
`endif

    ////////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
    output logic           GSENSOR_CS_N,
    input logic [2:1]      GSENSOR_INT,
    output logic           GSENSOR_SCLK,
    inout  logic           GSENSOR_SDI,
    inout  logic           GSENSOR_SDO,
`endif

    ////////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
    inout logic [15:0]     ARDUINO_IO,
    inout logic            ARDUINO_RESET_N,
`endif

    ////////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
    inout logic [35:0]     GPIO
`endif
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
logic clk_1ms;
logic [9:0] x, y;
logic paddle1_on, paddle2_on, puck_on;
logic [11:0] rgb_paddle1, rgb_paddle2, rgb_puck;
logic [9:0] x_paddle1 = L_position + (paddlewidth/2);
logic [9:0] y_paddle1 = V_active/2;
logic [9:0] x_paddle2 = H_active-(R_position + (paddlewidth/2));
logic [9:0] y_paddle2 = V_active/2;
logic video_on, p_tick;
logic [3:0] p1_score, p2_score;
logic [1:0] game_state;
logic timer;

//=======================================================
//  Structural coding
//=======================================================
vga_sync v1 (
    .clk(MAX10_CLK1_50), 
    .hsync(VGA_HS), 
    .vsync(VGA_VS), 
    .x(x), 
    .y(y), 
    .video_on(video_on)
);

vga_display d1 (
	 .clk(MAX10_CLK1_50), 
	 .reset(SW[9]), 
	 .sw1(SW[8]), 
	 .x(x), 
	 .y(y), 
	 .video_on(video_on), 
	 .rgb({VGA_R,VGA_G,VGA_B}), 
	 .clk_1ms(clk_1ms), 
	 .paddle1_on(paddle1_on),
	 .paddle2_on(paddle2_on),
	 .puck_on(puck_on),
	 .rgb_paddle1(rgb_paddle1),
	 .rgb_paddle2(rgb_paddle2),
	 .rgb_puck(rgb_puck),
    .game_state(game_state),
	 .p1_score(p1_score),
	 .p2_score(p2_score));

clock_divider c1 (
    .clk(MAX10_CLK1_50), 
    .clk_1ms(clk_1ms)
);

puck b1 (
    .clk(MAX10_CLK1_50), 
    .clk_1ms(clk_1ms), 
    .reset(SW[0]), 
    .x(x), 
    .y(y),  
    .puck_on(puck_on), 
    .rgb_puck(rgb_puck),
    .x_paddle1(x_paddle1), 
    .x_paddle2(x_paddle2), 
    .y_paddle1(y_paddle1), 
    .y_paddle2(y_paddle2),
    .p1_score(p1_score), 
    .p2_score(p2_score), 
    .game_state(game_state)
);

game_state gs (
    .clk(MAX10_CLK1_50), 
    .clk_1ms(clk_1ms), 
    .reset(SW[0]), 
    .p1_score(p1_score), 
    .p2_score(p2_score),
    .timer(timer), 
    .game_state(game_state)
);

score_display  ( 
	 .clk(MAX10_CLK1_50),
	 .clk_1ms(clk_1ms),
	 .reset(SW[0]),
	 .p1_score(p1_score),
	 .p2_score(p2_score),
	 .seg1(HEX0),
	 .seg2(HEX1)
);
	

Timer tmr (
    .reset(SW[0]), 
    .clk(MAX10_CLK1_50), 
    .timer(timer), 
    .seg_left(HEX5), 
    .seg_right(HEX4)
);

//===== Declarations
localparam int SPI_CLK_FREQ  = 200;  // SPI Clock (Hz)
localparam int UPDATE_FREQ   = 1;    // Sampling frequency (Hz)

// clks and reset
logic reset_n;
logic clk, spi_clk, spi_clk_out;

// output data
logic data_update;
logic [15:0] data_x, data_y;

//===== Phase-locked Loop (PLL) instantiation. Code was copied from a module
//      produced by Quartus' IP Catalog tool.
pll ip_inst (
    .inclk0 ( MAX10_CLK1_50 ),
    .c0 ( clk ),                 // 25 MHz, phase   0 degrees
    .c1 ( spi_clk ),             //  2 MHz, phase   0 degrees
    .c2 ( spi_clk_out )          //  2 MHz, phase 270 degrees
);

//===== Instantiation of the spi_control module which provides the logic to 
//      interface to the accelerometer.
spi_control #(     // parameters
    .SPI_CLK_FREQ   (SPI_CLK_FREQ),
    .UPDATE_FREQ    (UPDATE_FREQ)
) spi_ctrl (      // port connections
    .reset_n    (reset_n),
    .clk        (clk),
    .spi_clk    (spi_clk),
    .spi_clk_out(spi_clk_out),
    .data_update(data_update),
    .data_x     (data_x),
    .data_y     (data_y),
    .SPI_SDI    (GSENSOR_SDI),
    .SPI_SDO    (GSENSOR_SDO),
    .SPI_CSN    (GSENSOR_CS_N),
    .SPI_CLK    (GSENSOR_SCLK),
    .interrupt  (GSENSOR_INT)
);

//===== Main block
//      To make the module do something visible, the 16-bit data_x is 
//      displayed on four of the HEX displays in hexadecimal format.

// Pressing KEY0 freezes the accelerometer's output
assign reset_n = (!SW[1]);

localparam int H_active = 640;
localparam int V_active = 480;

localparam int paddlewidth = 15;
localparam int paddleheight = 60;

localparam int L_position = 20;
localparam int R_position = 20;

always_ff @ (posedge clk_1ms)
begin
    if(!SW[0])
    begin
        x_paddle1 <= L_position + (paddlewidth/2);
        y_paddle1 <= V_active/2;
    end
    else if (!KEY[0] && y_paddle1-(paddleheight/2) > 0)
        y_paddle1 <= y_paddle1-1;
    else if (!KEY[1] && y_paddle1+(paddleheight/2) < V_active)
        y_paddle1 <= y_paddle1+1;
    else 
        y_paddle1 <= y_paddle1;
end

assign paddle1_on = (x >= x_paddle1-(paddlewidth/2) && x <= x_paddle1+(paddlewidth/2) && y >= y_paddle1-(paddleheight/2) && y < y_paddle1+(paddleheight/2))?1'b1:1'b0;

assign rgb_paddle1 = 12'b000011110000; 

//Second padlle
always_ff @ (posedge clk_1ms)
begin
    if(!SW[0])
    begin    
        x_paddle2 <= H_active-(R_position + (paddlewidth/2));
        y_paddle2 <= V_active/2;
    end
    else if (data_y[12] && y_paddle2-(paddleheight/2) > 0)
        y_paddle2 <= y_paddle2-1;
    else if (!data_y[12] && y_paddle2+(paddleheight/2) < V_active )
        y_paddle2 <= y_paddle2+1;
    else 
        y_paddle2 <= y_paddle2;
end


assign paddle2_on = (x >= x_paddle2-(paddlewidth/2) && x <= x_paddle2+(paddlewidth/2) && y >= y_paddle2-(paddleheight/2) && y < y_paddle2+(paddleheight/2))?1'b1:1'b0;
assign rgb_paddle2 = 12'b110000001100; //orange =12'bb111101110000
endmodule
